SELECT
    SAFE_CAST(INSCMUNIC AS INT64) AS INSCMUNIC,
    SAFE_CAST(NUMGUIA AS INT64) AS NUMGUIA,
    SAFE_CAST(COMPETENCIA AS STRING) AS COMPETENCIA,
    SAFE_CAST(CODRECEITA AS STRING) AS CODRECEITA,
    SAFE_CAST(DTVENC AS STRING) AS DTVENC,
    SAFE_CAST(DTPGTO AS STRING) AS DTPGTO,
    SAFE_CAST(TRIBUTO AS FLOAT64) AS TRIBUTO,
    SAFE_CAST(VLPAGO AS FLOAT64) AS VLPAGO,
    SAFE_CAST(MORA AS FLOAT64) AS MORA,
    SAFE_CAST(MULTA AS FLOAT64) AS MULTA,
    SAFE_CAST(BANCO AS INT64) AS BANCO,
    SAFE_CAST(PROCESSO AS STRING) AS PROCESSO


FROM `rj-smfp.atividade_economica_sinae_staging.vw_clf_arrecad`