SELECT
    SAFE_CAST(COD_GRUPO AS STRING) AS COD_GRUPO,
    SAFE_CAST(DESC_GRUPO AS STRING) AS DESC_GRUPO,
    SAFE_CAST(COD_SUB_GRUPO AS STRING) AS COD_SUB_GRUPO,
    SAFE_CAST(DESC_SUB_GRUPO AS STRING) AS DESC_SUB_GRUPO,
    SAFE_CAST(COD_ATIVIDADE AS INT64) AS COD_ATIVIDADE,
    SAFE_CAST(DESC_ATIVIDADE AS STRING) AS DESC_ATIVIDADE,
    SAFE_CAST(STATUS AS STRING) AS STATUS,
    SAFE_CAST(DIVISAO AS STRING) AS DIVISAO


FROM `rj-smfp.atividade_economica_sinae_staging.vw_clf_ativ_econ`