{{
    config(
        alias='empresas',
        schema='brutos_ergon'
    )
}}

SELECT
    SAFE_CAST(REGEXP_REPLACE(CAST(t.EMPRESA AS STRING), r'\.0$', '') AS STRING) AS id_empresa,
    SAFE_CAST(t.NOME AS STRING) AS nome_empresa,
    SAFE_CAST(t.FANTASIA AS STRING) AS sigla,
    SAFE_CAST(t.RAZAO AS STRING) AS razao_social,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.CGC AS STRING), r'\.0$', '') AS STRING) AS cnpj,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.ATIV_ECON AS STRING), r'\.0$', '') AS STRING) AS atividade_economica,

    -- Colunas novas do schema
    SAFE_CAST(t._airbyte_extracted_at AS DATE) AS updated_at,
    SAFE_CAST(t.CEP AS STRING) AS cep,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.DDD AS STRING), r'\.0$', '') AS STRING) AS ddd,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.FAX AS STRING), r'\.0$', '') AS STRING) AS fax,
    SAFE_CAST(t.WEB AS STRING) AS web,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.CNAE AS STRING), r'\.0$', '') AS STRING) AS cnae,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.FONE AS STRING), r'\.0$', '') AS STRING) AS fone,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.BANCO AS STRING), r'\.0$', '') AS STRING) AS banco,
    SAFE_CAST(t.CONTA AS STRING) AS conta,
    SAFE_CAST(t.EMAIL AS STRING) AS email,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.RAMAL AS STRING), r'\.0$', '') AS STRING) AS ramal,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.ID_REG AS STRING), r'\.0$', '') AS STRING) AS id_reg,
    SAFE_CAST(t.AGENCIA AS STRING) AS agencia,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.NAT_JUR AS STRING), r'\.0$', '') AS STRING) AS nat_jur,
    SAFE_CAST(t.CPF_RESP AS STRING) AS cpf_resp,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.NUMENDER AS STRING), r'\.0$', '') AS STRING) AS numender,
    SAFE_CAST(t.PONTPROC AS STRING) AS pontproc,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.PONTPUBL AS STRING), r'\.0$', '') AS STRING) AS pontpubl,
    SAFE_CAST(t.UF_SIGLA AS STRING) AS uf_sigla,
    SAFE_CAST(t.MUNICIPIO AS STRING) AS municipio,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.LOG_CODIGO AS STRING), r'\.0$', '') AS STRING) AS log_codigo,
    SAFE_CAST(t.COMPLEMENTO AS STRING) AS complemento,
    SAFE_CAST(t.RESPONSAVEL AS STRING) AS responsavel,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.CAIXA_POSTAL AS STRING), r'\.0$', '') AS STRING) AS caixa_postal,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.ID_DOCUMENTO AS STRING), r'\.0$', '') AS STRING) AS id_documento,
    SAFE_CAST(t.FLEX_CAMPO_03 AS STRING) AS flex_campo_03,
    SAFE_CAST(t.FLEX_CAMPO_04 AS STRING) AS flex_campo_04,
    SAFE_CAST(t.FLEX_CAMPO_05 AS STRING) AS flex_campo_05,
    SAFE_CAST(t.FLEX_CAMPO_06 AS STRING) AS flex_campo_06,
    SAFE_CAST(t.FLEX_CAMPO_07 AS STRING) AS flex_campo_07,
    SAFE_CAST(t.FLEX_CAMPO_08 AS STRING) AS flex_campo_08,
    SAFE_CAST(REGEXP_REPLACE(CAST(t.CGC_DECLARANTE AS STRING), r'\.0$', '') AS STRING) AS cgc_declarante,
    SAFE_CAST(t.MBAIRRO_CODIGO AS STRING) AS mbairro_codigo,
    SAFE_CAST(t.NOMELOGRADOURO AS STRING) AS nomelogradouro,
    SAFE_CAST(t.TIPOLOGRADOURO AS STRING) AS tipologradouro,
    SAFE_CAST(t.MUNICIPIO_CODIGO AS STRING) AS municipio_codigo
FROM `rj-smfp.brutos_ergon_staging.VW_DLK_ERG_EMPRESAS` AS t