SELECT
    SAFE_CAST(REGEXP_REPLACE(TRIM(cd_orgao), r'\.0$', '') AS STRING) AS id_orgao,
    SAFE_CAST(REGEXP_REPLACE(TRIM(cd_orgao_pai), r'\.0$', '') AS STRING) AS id_orgao_pai,
    SAFE_CAST(TRIM(cd_secretaria_sdi) AS STRING) AS cd_secretaria_sdi,
    SAFE_CAST(TRIM(cep) AS STRING) AS cep,
    SAFE_CAST(REGEXP_REPLACE(TRIM(cnes), r'\.0$', '') AS STRING) AS id_cnes,
    SAFE_CAST(TRIM(complemento) AS STRING) AS complemento_endereco,
    SAFE_CAST(TRIM(descricao) AS STRING) AS descricao_orgao,
    SAFE_CAST(TRIM(ds_tipo_orgao) AS STRING) AS descricao_tipo_orgao,
    SAFE_CAST(DATE(dt_responsavel) AS DATE) AS data_cadastramento,
    SAFE_CAST(TRIM(email) AS STRING) AS email_orgao,
    SAFE_CAST(TRIM(endereco) AS STRING) AS endereco_orgao,
    SAFE_CAST(TRIM(fax1) AS STRING) AS fax_1,
    SAFE_CAST(TRIM(fax2) AS STRING) AS fax_2,
    SAFE_CAST(TRIM(matricula_responsavel) AS STRING) AS matricula_responsavel,
    SAFE_CAST(TRIM(nm_responsavel) AS STRING) AS nome_responsavel,
    SAFE_CAST(REGEXP_REPLACE(TRIM(numero_porta), r'\.0$', '') AS INT64) AS numero_porta,
    SAFE_CAST(TRIM(sigla) AS STRING) AS sigla_orgao,
    SAFE_CAST(TRIM(st_status) AS STRING) AS status_orgao,
    SAFE_CAST(TRIM(tel1) AS STRING) AS telefone_1,
    SAFE_CAST(TRIM(tel2) AS STRING) AS telefone_2,
    SAFE_CAST(TRIM(tp_orgao) AS STRING) AS tipo_orgao,
    SAFE_CAST(TRIM(tp_unidade) AS STRING) AS tipo_unidade,
FROM `rj-smfp.compras_materiais_servicos_sigma_staging.orgao` AS t